export const TEST_IDS = {
  sidebar: 'sidebar',
  sidebarToggle: 'sidebar-toggle',
  navDashboard: 'nav-dashboard',
  navNotas: 'nav-notas',
  navConferencia: 'nav-conferencia',
  navReconhecimento: 'nav-reconhecimento',
  navProdutos: 'nav-produtos',
  navFornecedores: 'nav-fornecedores',
  navEquivalencias: 'nav-equivalencias',
  statConferidas: 'stat-conferidas-hoje',
  statPendentes: 'stat-pendentes',
  statTempoMedio: 'stat-tempo-medio',
  statDivergencias: 'stat-divergencias',
  statSemVinculo: 'stat-sem-vinculo',
  statPrecisao: 'stat-precisao',
  xmlUploadInput: 'xml-upload-input',
  xmlUploadButton: 'xml-upload-button',
  seedDataButton: 'seed-data-button',
  downloadSampleXml: 'download-sample-xml',
  notasList: 'notas-list',
  scannerInput: 'scanner-input-field',
  conferenceTable: 'conference-table',
  confirmMatchButton: 'confirm-match-button',
  finalizeButton: 'finalize-conference-button',
  startConferenceButton: 'start-conference-button',
  productSearchInput: 'product-search-input',
  addProductButton: 'add-product-button',
  productsTable: 'products-table',
  supplierSearchInput: 'supplier-search-input',
  addSupplierButton: 'add-supplier-button',
  suppliersTable: 'suppliers-table',
  equivalencesTable: 'equivalences-table',
  recognitionFilterFornecedor: 'recognition-filter-fornecedor',
  recognitionConfirmButton: 'recognition-confirm-button',
  bindingStartConferenceBtn: 'binding-start-conference-btn',
  bindingPendingTable: 'binding-pending-table',
  bindingLinkedTable: 'binding-linked-table',
  bindingDialogConfirm: 'binding-dialog-confirm',
  bindingCodeInput: 'binding-code-input',
  bindingDescSearch: 'binding-desc-search',
};

export const HOME = { emergentLink: 'emergent-link' };
